### ISSUE TITLE
Option to limit carousel to one item on small screens

### ISSUE THREAD

**Issue by rsefer** [atacrawl/lunacy#3]
The difference between large screens:

![image](https://cloud.githubusercontent.com/assets/539765/3431995/ceab1502-006f-11e4-8506-c5f109650609.png)

and small screens:

![image](https://cloud.githubusercontent.com/assets/539765/3431999/df0909b8-006f-11e4-9669-e73899cb30e7.png)

is great. It would be nice to be able to collapse the carousel to a single visible item on screens smaller than X (maybe < 768px by default?). In this example, on small screens the user would see Box 19 span the entire width of the carousel and the next (right) arrow would switch to Box 20.

**Comment by atacrawl** [comment]
The reason I abandoned Slick and wrote Lunacy instead is because Slick uses Javascript to reassign all your widths. This was causing a ton of issues, considering the content I wanted to display had very specific widths (Instagram photos/data).

Long story short, Lunacy's JS just sets up the mechanism and lets CSS handle everything else (i.e. everything that it's supposed to). There are CSS declarations for when there's only one item in the carousel that could easily be transferred to a media query. Perhaps I need to do a better job in creating an agnostic "theme" for Lunacy, then layering display options (and additional CSS where appropriate) on top. And I also need to determine where the delineation is between what the JS provides and what's on the user to apply via CSS.
